# Generated by Django 4.0.4 on 2022-06-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
