# Generated by Django 4.0.4 on 2022-06-06 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('access', '0002_accesslog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='employees.employee'),
        ),
    ]
