# Generated by Django 4.0.4 on 2022-06-09 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('access', '0004_alter_accesslog_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='employees.employee'),
        ),
    ]
